In [53]:
import pandas as pd
import numpy as np

In [54]:
test_files = ['Simulation_1.csv', 'Simulation_2.csv', 'Simulation_3.csv', 'Specific_Offshores.csv', 'Specific_Onshores.csv']
columns = [pd.read_csv(test_file, sep='\t').columns.to_list() for test_file in test_files]
columns = list(set([col for cols in columns for col in cols]))
columns

['Total VBS',
 'Mcap Ratio',
 'xUSD to onshore',
 'Max Onshore xUSD',
 'Error Message',
 'Max Onshore XHV',
 'Mcap VBS',
 'XHV Supply',
 'XHV Price',
 'XHV Mcap',
 'Max Offshore XHV',
 'Spread Ratio',
 'xUSD (vault)',
 'XHV to offshore',
 'Collateral Needed (XHV)',
 'xAssets Mcap',
 'Shore Type',
 'XHV (vault)',
 'Slippage VBS',
 'Spread VBS']

In [55]:
sim1_df = pd.read_csv('Simulation_1.csv', sep='\t')
sim1_df

,Shore Type,XHV (vault),xUSD (vault),XHV Supply,XHV Price,XHV Mcap,xAssets Mcap,Mcap Ratio,Spread Ratio,Mcap VBS,Spread VBS,Slippage VBS,Total VBS,Max Offshore XHV,Max Onshore xUSD,Max Onshore XHV,Collateral Needed (XHV)
0,Onshore,500000.00,15000000.00,28500000.00,0.42,11970000.00,16000000.00,1.3367,0.0000,46.2459,50.4641,0.0000,50.4641,0.0,4161.37,9908.02,0
1,Onshore,509908.02,14995838.63,28509908.02,0.56,15965548.49,15995838.63,1.0019,0.0000,40.0379,44.2562,0.0000,44.2562,0.0,6452.17,11521.73,0
2,Onshore,521429.75,14989386.46,28521429.75,0.48,13690286.28,15989386.46,1.1679,0.0000,43.2284,47.4467,0.0000,47.4467,0.0,5275.10,10989.79,0
3,Onshore,532419.54,14984111.36,28532419.54,0.61,17404775.92,15984111.36,0.9184,0.0816,38.3328,43.4500,0.3003,43.7502,0.0,7423.23,12169.23,0
4,Onshore,544588.77,14976688.13,28544588.77,0.52,14843186.16,15976688.13,1.0764,0.0000,41.4992,45.7175,0.0000,45.7175,0.0,6194.26,11912.04,0
5,Onshore,556500.81,14970493.87,28556500.81,0.50,14278250.41,15970493.87,1.1185,0.0000,42.3040,46.5223,0.0000,46.5223,0.0,5981.01,11962.02,0
6,Onshore,568462.83,14964512.86,28568462.83,0.42,11998754.39,15964512.86,1.3305,0.0000,46.1392,50.3574,0.0000,50.3574,0.0,4741.19,11288.55,0

In [56]:
sim2_df = pd.read_csv('Simulation_2.csv', sep='\t')
sim2_df

,Shore Type,XHV (vault),xUSD (vault),XHV Supply,XHV Price,XHV Mcap,xAssets Mcap,Mcap Ratio,Spread Ratio,Mcap VBS,Spread VBS,Slippage VBS,Total VBS,Max Offshore XHV,Max Onshore xUSD,Max Onshore XHV,Collateral Needed (XHV)
0,Offshore,2014564.00,0.00,26281886.00,7.45,1.958001e+08,656994.00,0.0034,0.9966,1.0000,0.0000,5.3321,6.3321,274753.40,0.00,0.00,0
1,Offshore,1739810.60,2046912.83,26007132.60,3.66,9.518611e+07,2703906.83,0.0284,0.9716,1.0000,0.0000,2.2719,3.2719,405554.49,0.00,0.00,0
2,Offshore,1334256.11,3531242.26,25601578.11,1.38,3.533018e+07,4188236.26,0.1185,0.8815,2.0236,0.0000,2.8950,4.9186,225393.59,0.00,0.00,0
3,Onshore,1108862.52,3842285.41,25376184.52,0.86,2.182352e+07,4499279.41,0.2062,0.7938,3.2451,11.3709,0.2265,11.5974,0.00,82210.90,95594.07,0
4,Onshore,1204456.59,3760074.51,25471778.59,0.56,1.426420e+07,4417068.51,0.3097,0.6903,5.1535,12.8927,0.2474,13.1402,0.00,51321.60,91645.71,0
5,Onshore,1296102.30,3708752.91,25563424.30,0.48,1.227044e+07,4365746.91,0.3558,0.6442,6.2164,13.7820,0.2610,14.0430,0.00,44293.95,92279.06,0
6,Onshore,1388381.36,3664458.96,25655703.36,0.61,1.564998e+07,4321452.96,0.2761,0.7239,4.4690,12.3340,0.2605,12.5945,0.00,67229.95,110213.03,0
7,Onshore,1498594.39,3597229.01,25765916.39,0.52,1.339828e+07,4254223.01,0.3175,0.6825,5.3242,13.0340,0.2749,13.3089,0.00,58539.83,112576.60,0
8,Onshore,1611170.99,3538689.18,25878492.99,0.50,1.293925e+07,4195683.18,0.3243,0.6757,5.4739,13.1583,0.2851,13.4434,0.00,59910.38,119820.76,0
9,Onshore,1730991.75,3478778.80,25998313.75,0.42,1.091929e+07,4135772.80,0.3788,0.6212,6.8037,14.2823,0.3013,14.5836,0.00,49840.81,118668.60,0

In [57]:
sim3_df = pd.read_csv('Simulation_3.csv', sep='\t')
sim3_df

,Shore Type,XHV (vault),xUSD (vault),XHV Supply,XHV Price,XHV Mcap,xAssets Mcap,Mcap Ratio,Spread Ratio,Mcap VBS,Spread VBS,Slippage VBS,Total VBS,Max Offshore XHV,Max Onshore xUSD,Max Onshore XHV,Collateral Needed (XHV)
0,Onshore,500000.00,16000000.00,28500000.00,0.56,15960000.00,18000000.00,1.1278,0.0,42.4795,46.6978,0.0,46.6978,0.0,5996.00,10707.14,0
1,Onshore,510707.14,15994004.00,28510707.14,0.50,14255353.57,17994004.00,1.2623,0.0,44.9402,49.1585,0.0,49.1585,0.0,5194.50,10389.00,0
2,Onshore,521096.14,15988809.50,28521096.14,0.48,13690126.15,17988809.50,1.3140,0.0,45.8519,50.0702,0.0,50.0702,0.0,4995.51,10407.31,0
3,Onshore,531503.45,15983813.99,28531503.45,0.40,11412601.38,17983813.99,1.5758,0.0,50.2121,54.4304,0.0,54.4304,0.0,3905.93,9764.83,0
4,Onshore,541268.28,15979908.06,28541268.28,0.35,9989443.90,17979908.06,1.7999,0.0,53.6640,57.8823,0.0,57.8823,0.0,3272.92,9351.20,0
5,Onshore,550619.48,15976635.14,28550619.48,0.30,8565185.84,17976635.14,2.0988,0.0,57.9490,62.1673,0.0,62.1673,0.0,2657.12,8857.07,0
6,Onshore,559476.55,15973978.02,28559476.55,0.25,7139869.14,17973978.02,2.5174,0.0,63.4654,67.6837,0.0,67.6837,0.0,2066.51,8266.04,0
7,Onshore,567742.59,15971911.51,28567742.59,0.20,5713548.52,17971911.51,3.1455,0.0,70.9421,75.1604,0.0,75.1604,0.0,1510.75,7553.75,0
8,Onshore,575296.34,15970400.76,28575296.34,0.15,4286294.45,17970400.76,4.1925,0.0,81.9026,86.1209,0.0,86.1209,0.0,1002.02,6680.13,0
9,Onshore,581976.47,15969398.74,28581976.47,0.10,2858197.65,17969398.74,6.2870,0.0,100.2950,104.5140,0.0,104.5140,0.0,556.84,5568.40,0
10,Onshore,587544.87,15968841.90,28587544.87,0.05,1429377.24,17968841.90,12.5711,0.0,141.8230,146.0410,0.0,146.0410,0.0,201.16,4023.20,0
11,Onshore,591568.07,15968640.74,28591568.07,0.03,857747.04,17968640.74,20.9486,0.0,183.0790,187.2970,0.0,187.2970,0.0,94.75,3158.33,0
12,Onshore,594726.40,15968545.99,28594726.40,0.02,571894.53,17968545.99,31.4193,0.0,224.2120,228.4300,0.0,228.4300,0.0,52.07,2603.50,0
13,Onshore,597329.90,15968493.92,28597329.90,0.01,285973.30,17968493.92,62.8328,0.0,317.0680,321.2870,0.0,321.2870,0.0,18.59,1859.00,0

---

In [76]:
offshore_df = pd.read_csv('Specific_Offshores.csv', sep='\t')
print(offshore_df.info())
offshore_df#.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1368 entries, 0 to 1367
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Shore Type               1368 non-null   object
 1   XHV (vault)              1368 non-null   float64
 2   XHV to offshore          1368 non-null   float64
 3   xUSD (vault)             1368 non-null   float64
 4   xUSD to onshore          1368 non-null   float64
 5   XHV Supply               1368 non-null   float64
 6   XHV Price                1368 non-null   float64
 7   XHV Mcap                 1368 non-null   float64
 8   xAssets Mcap             1368 non-null   float64
 9   Mcap Ratio               1368 non-null   float64
 10  Spread Ratio             1368 non-null   float64
 11  Mcap VBS                 1368 non-null   float64
 12  Spread VBS               1368 non-null   float64
 13  Slippage VBS             1368 non-null   float64
 14  Total VBS                1368 non-null   float64
 15  Max Offshore XHV         1368 non-null   float64
 16  Max Onshore xUSD         1368 non-null   float64
 17  Collateral Needed (XHV)  1368 non-null   float64
 18  Error Message            219 non-null    object
dtypes: float64(17), object(2)
memory usage: 203.2+ KB
None

,XHV (vault),XHV to offshore,xUSD (vault),xUSD to onshore,XHV Supply,XHV Price,XHV Mcap,xAssets Mcap,Mcap Ratio,Spread Ratio,Mcap VBS,Spread VBS,Slippage VBS,Total VBS,Max Offshore XHV,Max Onshore xUSD,Collateral Needed (XHV)
count,1.368000e+03,1368.000000,1368.0,1368.0,1.368000e+03,1368.000000,1.368000e+03,1.368000e+03,1368.000000,1368.000000,1368.000000,1368.0,1368.000000,1368.000000,1368.0,1368.0,1.368000e+03
mean,6.890078e+05,97708.748648,0.0,0.0,2.075826e+07,4.587310,8.458911e+07,7.793095e+06,0.132429,0.867571,3.214962,0.0,1.041115,4.264264,0.0,0.0,2.968785e+05
std,1.011601e+06,140259.650763,0.0,0.0,5.409879e+06,4.462703,6.207038e+07,8.000698e+06,0.172114,0.172114,5.296873,0.0,1.029817,5.228722,0.0,0.0,5.129362e+05
min,5.000000e+00,0.700000,0.0,0.0,1.178146e+07,0.520000,1.213008e+07,7.051000e+03,0.000100,-0.187000,0.517300,0.0,0.003000,1.000000,0.0,0.0,0.000000e+00
25%,1.684000e+03,477.150000,0.0,0.0,1.426863e+07,2.040000,4.465730e+07,2.233922e+06,0.026700,0.852450,1.072800,0.0,0.106900,1.420900,0.0,0.0,2.684950e+02
50%,7.550200e+04,16818.150000,0.0,0.0,2.353672e+07,2.855000,6.789814e+07,2.873573e+06,0.061500,0.938500,1.655500,0.0,0.726250,2.844950,0.0,0.0,9.289020e+03
75%,1.220816e+06,155837.500000,0.0,0.0,2.540429e+07,4.857500,1.077188e+08,1.629882e+07,0.147550,0.973300,3.067000,0.0,1.865050,5.283525,0.0,0.0,3.718035e+05
max,4.177685e+06,581129.850000,0.0,0.0,2.815775e+07,25.300000,3.633189e+08,3.103154e+07,1.187000,0.999900,43.551800,0.0,4.290200,43.582500,0.0,0.0,3.548163e+06

In [82]:
offshore_df['Error Message'].unique()

array([nan, 'offshore amount greater than block limit',
       'incorrect offshore amount', 'not enough collateral available'],
      dtype=object)

In [80]:
# import math
# help(math.exp)

In [77]:
onshore_df = pd.read_csv('Specific_Onshores.csv', sep='\t')
onshore_df.head(13)
# onshore_df.describe()

,XHV (vault),XHV to offshore,xUSD (vault),xUSD to onshore,XHV Supply,XHV Price,XHV Mcap,xAssets Mcap,Mcap Ratio,Spread Ratio,Mcap VBS,Spread VBS,Slippage VBS,Total VBS,Max Offshore XHV,Max Onshore xUSD,Collateral Needed (XHV)
count,1.051000e+03,1051.0,1.051000e+03,1.051000e+03,1.051000e+03,1051.000000,1.051000e+03,1.051000e+03,1051.000000,1051.000000,1051.000000,1051.000000,1051.000000,1051.000000,1051.0,1051.0,1.051000e+03
mean,7.625491e+05,0.0,5.542360e+04,2.055735e+04,1.874774e+07,6.711037,1.090191e+08,1.076153e+07,0.148352,0.852160,3.336807,11.168477,0.027392,11.354205,0.0,0.0,3.143608e+04
std,8.397827e+05,0.0,3.089920e+05,8.356590e+04,5.004538e+06,5.340720,7.121250e+07,8.447781e+06,0.178694,0.177113,5.631860,4.937539,0.037179,5.085661,0.0,0.0,1.092614e+05
min,2.000000e+01,0.0,2.000000e+00,0.000000e+00,1.241722e+07,0.530000,1.492177e+07,1.073300e+04,0.000100,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000e+00
25%,9.907650e+04,0.0,2.975000e+02,2.000000e+02,1.411406e+07,2.520000,5.404065e+07,3.184291e+06,0.044300,0.835800,1.103900,9.838700,0.005500,9.901400,0.0,0.0,4.468100e+02
50%,4.747040e+05,0.0,1.809000e+03,1.129100e+03,1.600266e+07,4.630000,9.566445e+07,7.978656e+06,0.089300,0.910600,1.658800,10.204000,0.012700,10.250700,0.0,0.0,2.247670e+03
75%,1.224395e+06,0.0,1.005750e+04,6.924050e+03,2.392975e+07,10.300000,1.527054e+08,1.793169e+07,0.164200,0.956200,2.623200,10.833900,0.032750,11.048000,0.0,0.0,1.357678e+04
max,4.169034e+06,0.0,4.127272e+06,1.005319e+06,2.815428e+07,26.300000,3.660219e+08,3.107670e+07,1.158300,0.999900,43.119300,47.337600,0.261600,47.337600,0.0,0.0,1.661692e+06

In [61]:
help(onshore_df.drop)

Help on method drop in module pandas.core.frame:

drop(labels: 'IndexLabel' = None, axis: 'Axis' = 0, index: 'IndexLabel' = None, columns: 'IndexLabel' = None, level: 'Level' = None, inplace: 'bool' = False, errors: 'IgnoreRaise' = 'raise') -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by specifying directly index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the `user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as a list-like.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-like
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        inplace and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        DataFrame without the removed index or column labels or
        None if ``inplace=True``.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4),
    ...                   columns=['A', 'B', 'C', 'D'])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(['B', 'C'], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=['B', 'C'])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(levels=[['lama', 'cow', 'falcon'],
    ...                              ['speed', 'weight', 'length']],
    ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
    ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
    >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
    ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
    ...                         [250, 150], [1.5, 0.8], [320, 250],
    ...                         [1, 0.8], [0.3, 0.2]])
    >>> df
                    big     small
    lama    speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=('falcon', 'weight'))
                    big     small
    lama    speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index='cow', columns='small')
                    big
    lama    speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index='length', level=1)
                    big     small
    lama    speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [62]:
onshore_df[onshore_df['xAssets Mcap'] == 0]

Empty DataFrame
Columns: [Shore Type, XHV (vault), XHV to offshore, xUSD (vault), xUSD to onshore, XHV Supply, XHV Price, XHV Mcap, xAssets Mcap, Mcap Ratio, Spread Ratio, Mcap VBS, Spread VBS, Slippage VBS, Total VBS, Max Offshore XHV, Max Onshore xUSD, Collateral Needed (XHV), Error Message]
Index: []

In [63]:
onshore_df.drop(onshore_df[onshore_df['xAssets Mcap'] == 0].index).reset_index()

,index,Shore Type,XHV (vault),XHV to offshore,xUSD (vault),xUSD to onshore,XHV Supply,XHV Price,XHV Mcap,xAssets Mcap,Mcap Ratio,Spread Ratio,Mcap VBS,Spread VBS,Slippage VBS,Total VBS,Max Offshore XHV,Max Onshore xUSD,Collateral Needed (XHV),Error Message
0,0,Onshore Specific,807581.0,0.0,478.0,334.6,25463900.0,3.57,9.090612e+07,2324317.0,0.0256,0.9744,0.9491,9.7437,0.0059,9.7496,0.0,0.0,913.79,NaN
1,1,Onshore Specific,378549.0,0.0,27333.0,19133.1,13636644.0,2.12,2.890969e+07,2902777.0,0.1005,0.8996,1.8038,10.3217,0.0853,10.4071,0.0,0.0,93924.25,NaN
2,2,Onshore Specific,147904.0,0.0,3.0,0.0,14034002.0,12.70,1.782318e+08,3837296.0,0.0216,0.9784,0.0000,0.0000,0.0000,0.0000,0.0,0.0,0.00,incorrect onshore amount
3,3,Onshore Specific,2815869.0,0.0,23176.0,23176.0,26837284.0,2.65,7.111880e+07,1685119.0,0.0237,0.9763,0.9265,9.7280,0.0554,9.7835,0.0,0.0,85563.13,NaN
4,4,Onshore Specific,776499.0,0.0,30454.0,30454.0,15081278.0,14.20,2.141541e+08,25496037.0,0.1192,0.8809,2.0299,10.4789,0.0403,10.5192,0.0,0.0,22559.94,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1047,1047,Onshore Specific,282148.0,0.0,14718.0,10302.6,13399897.0,2.32,3.108776e+07,2209015.0,0.0710,0.9289,1.4645,10.0910,0.0586,10.1496,0.0,0.0,45072.21,NaN
1048,1048,Onshore Specific,1581924.0,0.0,9978.0,6984.6,15905566.0,11.30,1.797329e+08,23018368.0,0.1280,0.8719,2.1429,10.5584,0.0213,10.5797,0.0,0.0,6539.39,NaN
1049,1049,Onshore Specific,2470802.0,0.0,480.0,336.0,23422233.0,3.25,7.612226e+07,4088706.0,0.0537,0.9463,1.2699,9.9605,0.0067,9.9672,0.0,0.0,1030.45,NaN
1050,1050,Onshore Specific,12220.0,0.0,7000.0,556.5,25948809.0,1.00,2.594881e+07,15665037.0,0.6015,0.3963,15.3209,21.9224,0.0279,21.9503,0.0,0.0,12215.34,NaN
1051,1051,Onshore Specific,829749.0,0.0,1522.0,1522.0,15132847.0,14.20,2.148864e+08,24836229.0,0.1157,0.8844,1.9870,10.4488,0.0090,10.4578,0.0,0.0,1120.90,NaN

In [89]:
onshore_df['Error Message'].unique()

array([nan, 'incorrect onshore amount',
       'not enough xUSD available to onshore',
       'not enough collateral available'], dtype=object)

In [65]:
{col: "TODO" for col in onshore_df.columns.to_list()}

{'Shore Type': 'TODO',
 'XHV (vault)': 'TODO',
 'XHV to offshore': 'TODO',
 'xUSD (vault)': 'TODO',
 'xUSD to onshore': 'TODO',
 'XHV Supply': 'TODO',
 'XHV Price': 'TODO',
 'XHV Mcap': 'TODO',
 'xAssets Mcap': 'TODO',
 'Mcap Ratio': 'TODO',
 'Spread Ratio': 'TODO',
 'Mcap VBS': 'TODO',
 'Spread VBS': 'TODO',
 'Slippage VBS': 'TODO',
 'Total VBS': 'TODO',
 'Max Offshore XHV': 'TODO',
 'Max Onshore xUSD': 'TODO',
 'Collateral Needed (XHV)': 'TODO',
 'Error Message': 'TODO'}

In [66]:
offshore_df = pd.read_csv('Specific_Offshores.csv', sep='\t')
offshore_df

,Shore Type,XHV (vault),XHV to offshore,xUSD (vault),xUSD to onshore,XHV Supply,XHV Price,XHV Mcap,xAssets Mcap,Mcap Ratio,Spread Ratio,Mcap VBS,Spread VBS,Slippage VBS,Total VBS,Max Offshore XHV,Max Onshore xUSD,Collateral Needed (XHV),Error Message
0,Offshore Specific,19057.0,3478.0,0.0,0.0,23997040.0,3.09,7.415085e+07,19482217.0,0.2627,0.7373,4.2145,0.0,0.2639,4.4784,0.0,0.0,19053.88,NaN
1,Offshore Specific,701.0,137.0,0.0,0.0,23998899.0,3.20,7.679648e+07,19480290.0,0.2540,0.7460,4.0477,0.0,0.0531,4.1008,0.0,0.0,698.81,NaN
2,Offshore Specific,400.0,73.0,0.0,0.0,24004639.0,2.98,7.153382e+07,19496206.0,0.2726,0.7274,4.3999,0.0,0.0377,4.4375,0.0,0.0,396.94,NaN
3,Offshore Specific,1392548.0,223873.0,0.0,0.0,21137010.0,2.92,6.172007e+07,6362054.0,0.1032,0.8968,1.8356,0.0,3.3846,5.2202,0.0,0.0,1392542.38,NaN
4,Offshore Specific,1684.0,715.0,0.0,0.0,23519089.0,4.01,9.431155e+07,61083.0,0.0006,0.9994,0.5536,0.0,0.6502,1.2038,0.0,0.0,1575.69,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1364,Offshore Specific,1508585.0,207984.0,0.0,0.0,16199749.0,6.40,1.036784e+08,26968159.0,0.2600,0.7400,4.1660,0.0,2.4490,6.6150,0.0,0.0,0.00,not enough collateral available
1365,Offshore Specific,1376697.0,155182.3,0.0,0.0,21120801.0,2.68,5.660375e+07,6275200.0,0.1107,0.8893,1.9294,0.0,2.7234,4.6528,0.0,0.0,877208.63,NaN
1366,Offshore Specific,59964.0,19074.0,0.0,0.0,13396913.0,1.86,2.491826e+07,2344097.0,0.0943,0.9057,1.7290,0.0,0.3863,2.1153,0.0,0.0,59422.02,NaN
1367,Offshore Specific,725458.0,84558.6,0.0,0.0,15025735.0,13.90,2.088577e+08,24445249.0,0.1174,0.8826,2.0051,0.0,2.3241,4.3291,0.0,0.0,450624.34,NaN
1368,Offshore Specific,541.0,102.9,0.0,0.0,24005035.0,2.98,7.153500e+07,19633377.0,0.2745,0.7255,4.4370,0.0,0.0440,4.4800,0.0,0.0,0.00,not enough collateral available

In [67]:
offshore_df[offshore_df['xAssets Mcap'] == 0]

Empty DataFrame
Columns: [Shore Type, XHV (vault), XHV to offshore, xUSD (vault), xUSD to onshore, XHV Supply, XHV Price, XHV Mcap, xAssets Mcap, Mcap Ratio, Spread Ratio, Mcap VBS, Spread VBS, Slippage VBS, Total VBS, Max Offshore XHV, Max Onshore xUSD, Collateral Needed (XHV), Error Message]
Index: []

In [68]:
{col: "TODO" for col in offshore_df.columns.to_list()}

{'Shore Type': 'TODO',
 'XHV (vault)': 'TODO',
 'XHV to offshore': 'TODO',
 'xUSD (vault)': 'TODO',
 'xUSD to onshore': 'TODO',
 'XHV Supply': 'TODO',
 'XHV Price': 'TODO',
 'XHV Mcap': 'TODO',
 'xAssets Mcap': 'TODO',
 'Mcap Ratio': 'TODO',
 'Spread Ratio': 'TODO',
 'Mcap VBS': 'TODO',
 'Spread VBS': 'TODO',
 'Slippage VBS': 'TODO',
 'Total VBS': 'TODO',
 'Max Offshore XHV': 'TODO',
 'Max Onshore xUSD': 'TODO',
 'Collateral Needed (XHV)': 'TODO',
 'Error Message': 'TODO'}

In [69]:
#pd.testing.assert_frame_equal(df1, df2, check_exact=False, check_less_precise=3)
offshore_df.dtypes == float
offshore_df.columns[offshore_df.dtypes == float]

Index(['XHV (vault)', 'XHV to offshore', 'xUSD (vault)', 'xUSD to onshore',
       'XHV Supply', 'XHV Price', 'XHV Mcap', 'xAssets Mcap', 'Mcap Ratio',
       'Spread Ratio', 'Mcap VBS', 'Spread VBS', 'Slippage VBS', 'Total VBS',
       'Max Offshore XHV', 'Max Onshore xUSD', 'Collateral Needed (XHV)'],
      dtype='object')

In [70]:
10 ** 3

1000

In [71]:
offshore_df.dtypes.to_dict()# == float

{'Shore Type': dtype('O'),
 'XHV (vault)': dtype('float64'),
 'XHV to offshore': dtype('float64'),
 'xUSD (vault)': dtype('float64'),
 'xUSD to onshore': dtype('float64'),
 'XHV Supply': dtype('float64'),
 'XHV Price': dtype('float64'),
 'XHV Mcap': dtype('float64'),
 'xAssets Mcap': dtype('float64'),
 'Mcap Ratio': dtype('float64'),
 'Spread Ratio': dtype('float64'),
 'Mcap VBS': dtype('float64'),
 'Spread VBS': dtype('float64'),
 'Slippage VBS': dtype('float64'),
 'Total VBS': dtype('float64'),
 'Max Offshore XHV': dtype('float64'),
 'Max Onshore xUSD': dtype('float64'),
 'Collateral Needed (XHV)': dtype('float64'),
 'Error Message': dtype('O')}

In [72]:
help(offshore_df.astype)

Help on method astype in module pandas.core.generic:

astype(dtype, copy: 'bool_t' = True, errors: 'IgnoreRaise' = 'raise') -> 'NDFrameT' method of pandas.core.frame.DataFrame instance
    Cast a pandas object to a specified dtype ``dtype``.

    Parameters
    ----------
    dtype : data type, or dict of column name -> data type
        Use a numpy.dtype or Python type to cast entire pandas object to
        the same type. Alternatively, use {col: dtype, ...}, where col is a
        column label and dtype is a numpy.dtype or Python type to cast one
        or more of the DataFrame's columns to column-specific types.
    copy : bool, default True
        Return a copy when ``copy=True`` (be very careful setting
        ``copy=False`` as changes to values then may propagate to other
        pandas objects).
    errors : {'raise', 'ignore'}, default 'raise'
        Control raising of exceptions on invalid data for provided dtype.

        - ``raise`` : allow exceptions to be raised
        - ``ignore`` : suppress exceptions. On error return original object.

    Returns
    -------
    casted : same type as caller

    See Also
    --------
    to_datetime : Convert argument to datetime.
    to_timedelta : Convert argument to timedelta.
    to_numeric : Convert argument to a numeric type.
    numpy.ndarray.astype : Cast a numpy array to a specified type.

    Notes
    -----
    .. deprecated:: 1.3.0

        Using ``astype`` to convert from timezone-naive dtype to
        timezone-aware dtype is deprecated and will raise in a
        future version.  Use :meth:`Series.dt.tz_localize` instead.

    Examples
    --------
    Create a DataFrame:

    >>> d = {'col1': [1, 2], 'col2': [3, 4]}
    >>> df = pd.DataFrame(data=d)
    >>> df.dtypes
    col1    int64
    col2    int64
    dtype: object

    Cast all columns to int32:

    >>> df.astype('int32').dtypes
    col1    int32
    col2    int32
    dtype: object

    Cast col1 to int32 using a dictionary:

    >>> df.astype({'col1': 'int32'}).dtypes
    col1    int32
    col2    int64
    dtype: object

    Create a series:

    >>> ser = pd.Series([1, 2], dtype='int32')
    >>> ser
    0    1
    1    2
    dtype: int32
    >>> ser.astype('int64')
    0    1
    1    2
    dtype: int64

    Convert to categorical type:

    >>> ser.astype('category')
    0    1
    1    2
    dtype: category
    Categories (2, int64): [1, 2]

    Convert to ordered categorical type with custom ordering:

    >>> from pandas.api.types import CategoricalDtype
    >>> cat_dtype = CategoricalDtype(
    ...     categories=[2, 1], ordered=True)
    >>> ser.astype(cat_dtype)
    0    1
    1    2
    dtype: category
    Categories (2, int64): [2 < 1]

    Note that using ``copy=False`` and changing data on a new
    pandas object may propagate changes:

    >>> s1 = pd.Series([1, 2])
    >>> s2 = s1.astype('int64', copy=False)
    >>> s2[0] = 10
    >>> s1  # note that s1[0] has changed too
    0    10
    1     2
    dtype: int64

    Create a series of dates:

    >>> ser_date = pd.Series(pd.date_range('20200101', periods=3))
    >>> ser_date
    0   2020-01-01
    1   2020-01-02
    2   2020-01-03
    dtype: datetime64[ns]

In [73]:
(offshore_df['Spread Ratio'] * 10000).astype(int).astype(float) / 10000

0       0.7373
1       0.7460
2       0.7274
3       0.8968
4       0.9994
         ...
1364    0.7400
1365    0.8893
1366    0.9057
1367    0.8826
1368    0.7255
Name: Spread Ratio, Length: 1369, dtype: float64